App\Infrastructure\Persistence\Doctrine\Post\Post:
    
    collectionOperations:
        post:
            method: POST
            path: '/posts/create'
            messenger: true
            input: App\Infrastructure\Api\Post\CreatePost\CreatePostInput
            output: false
            validate: false
            status: 201
            openapi_context:
                summary: Create a user account
                requestBody:
                    required: true
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    title:
                                        type: string
                                        format: text
                                        required: true
                                    content:
                                        type: string
                                        format: text
                                        required: true
                                    publishedAt:
                                        type: string
                                        format: date-time
                                        required: false
                            example:
                                title: Title for test
                                content: Content for test
                                publishedAt: "2022-06-20T22:35:21Z"
                responses:
                    201:
                        description: Post created
                    400:
                        description: Invalid input
    
    itemOperations: [ ]
